spring.application.name=isp

# Database Configuration (Using Environment Variables)
spring.datasource.url=jdbc:mysql://localhost:3306/isp_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect